-- =====================================================================================
	-- Magnitude Analysis
-- =====================================================================================

-- Find total customers by country
SELECT country, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC


-- Find total customers by gender
SELECT gender, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC


-- Find total products by category
SELECT category, COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT
	category,
	AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC


-- What is the total revenue generated for each category?
SELECT
	dm.category,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dm
ON fs.product_key = dm.product_key
GROUP BY dm.category
ORDER BY total_revenue DESC

-- Find total revenue generated by each customer
SELECT
	dc.customer_key,
	dc.first_name,
	dc.last_name,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY 
		 dc.customer_key,
		 dc.first_name,
		 dc.last_name
ORDER BY total_revenue DESC

SELECT 
		 dc.customer_key,
		 dc.first_name,
		 dc.last_name,
		 country,
		 SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
WHERE first_name IN ('Jordan', 'Willie') AND last_name IN ('Turner', 'Xu')
GROUP BY 
		 dc.customer_key,
		 dc.first_name,
		 dc.last_name,
		 country
ORDER BY total_revenue DESC


-- What is the distribution of sold items accross countries?
SELECT
	dc.country,
	SUM(fs.quantity) AS total_sold_items
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY total_sold_items DESC
